#!/usr/bin/env python
from subprocess import call
import sys
import os

def fallback():
    args = " ".join(sys.argv[1:])
    command = 'lrn.py {}'.format(args)
    os.system(command)

try:
    status = call('rlwrap')
    if status == 0:
        args = " ".join(sys.argv[1:])
        command = 'rlwrap lrn.py {}'.format(args)
        os.system(command)
    else:
        fallback()
except:
    fallback()
