#!/usr/bin/python
from subprocess import call, STDOUT
import sys
import os

def fallback():
    args = " ".join(sys.argv[1:])
    command = 'lrn.py {}'.format(args)
    os.system(command)

try:
    status = call('rlwrap', stdout=open('/dev/null', 'w'), stderr=STDOUT)
    if status == 0:
        args = " ".join(sys.argv[1:])
        command = 'rlwrap lrn.py {}'.format(args)
        os.system(command)
    else:
        fallback()
except:
    fallback()
